default:
    api:
        twitter:
            consumer_key:  eGCunHb3MgjLiqJ32vPyjzqDy
            consumer_secret:  s0xd6egFQDdE5jLURyBnoFHybDzxJKbZtbEXtk8Jey2JjSSleq
            access_token_key: 798784794150588416-jfqoFhOAYXrJglKZmJYPY3dhhYHPhmF
            access_token_secret: FGnxrqqDcMPukWMOEiSFNnpTK7ZHsdmXaq2F7UqCvjbfP
        db: 
            ip_address: IP_ADDRESS 
            port: PORT 
            dbname: DBNAME 


